name: Trivy CVE Dependency Scanner

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  trivy-scan:
    uses: vmware-tanzu/carvel-release-scripts/.github/workflows/trivy-scan.yml@main
    with:
      repo: vmware-tanzu/carvel-vendir
      tool: vendir
      goVersion: 1.19.1
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      slackWebhookURL: ${{ secrets.SLACK_WEBHOOK_URL }}
